#import "../../lib.typ": *

= Title

#check("1a")[A randomized trial of Drug X versus placebo for Outcome Y: study protocol.]

= Administrative information

#check("2")[Protocol version 2.1, 15 January 2026.]

= Methods: Assignment of interventions

#check("21a")[The randomisation sequence will be generated by an independent statistician using a computer algorithm.]

#check("21b")[Simple randomisation will be used, with no stratification.]

#check("22")[Allocation will be concealed via a centralised, web-based randomisation system.]

#check("24a")[Participants, care providers, and outcome assessors will be blinded to group assignment.]

// Item 23 (Implementation) left uncovered on purpose, to show the
// "not covered" marker inside the Randomization group band.

= Ethics

#check("30")[Approval will be sought from the regional research ethics committee prior to enrolment.]
