#import "../../lib.typ": *

= Methods

#check("17a")[The allocation sequence was generated by an independent
  statistician using a computer-based random-number generator.]

#check("18")[Allocation was concealed using sequentially numbered, opaque,
  sealed envelopes.]

#pagebreak()

= Appendix: verbatim compliance excerpts

This appendix is not part of the official CONSORT grid (which only has a
page-number column) — it demonstrates `excerpt-of`, re-emitting the real
manuscript wording next to each item, for a journal that additionally
wants verbatim quotes.

*Item 17a* (Sequence generation): #excerpt-of("17a", quotes: true, show-page: true)

*Item 18* (Allocation concealment mechanism): #excerpt-of("18", quotes: true, show-page: true)

*Item 19* (Implementation) — never checked in this manuscript, default
`on-empty: none` renders nothing between the colon and the period: #excerpt-of("19").

*Item 20a* (Blinding) — never checked either, but with an explicit
fallback: #excerpt-of("20a", on-empty: [_(not reported)_]).
