#import "../../lib.typ": *
#import "../../../typst-contexture/lib.typ" as contexture

// Demonstrates excerpt-of(): re-emitting the real, verbatim content
// anchored by check(), e.g. for a supplementary "compliance appendix"
// listing exact wording next to each item --- not part of the official
// CONSORT grid (which only has a page-number column), so this lives in
// the manuscript itself, not in checklist.pdf.

#show: contexture.bundle.with(
  template: body => {
    set page(width: 16.6cm, height: auto, margin: 12pt)
    set text(size: 10.5pt)
    body
  },
  documents: (checklist(checklist: checklists.consort),),
)

= Methods

#check("17a")[The allocation sequence was generated by an independent
  statistician using a computer-based random-number generator.]

#check("18")[Allocation was concealed using sequentially numbered, opaque,
  sealed envelopes.]

= Appendix: verbatim compliance excerpts

*Item 17a* (Sequence generation): #excerpt-of("17a", quotes: true, show-page: true)

*Item 18* (Allocation concealment mechanism): #excerpt-of("18", quotes: true, show-page: true)

*Item 19* (Implementation) --- never checked in this manuscript, default
`on-empty: none` renders nothing between the colon and the period: #excerpt-of("19").

*Item 20a* (Blinding) --- never checked either, but with an explicit
fallback: #excerpt-of("20a", on-empty: [_(not reported)_]).
