#import "../../lib.typ": *

= Title and abstract

#check("1a")[Effect of Drug X on Outcome Y: a randomised controlled trial.]

#check("1b")[
  *Background*: Outcome Y remains poorly controlled with standard care.
  *Methods*: We conducted a two-arm, parallel-group randomised trial.
  *Results*: The mean difference in outcome Y was 4.2 points in favour of
  Drug X. *Conclusions*: Drug X improves outcome Y relative to placebo.
]

= Open science

#check("2")[Registered at ClinicalTrials.gov, NCT01234567, registered 2024-01-15.]

#check("3")[The protocol and statistical analysis plan are available at
  osf.io/example.]

// Item 4 (Data sharing) left uncovered on purpose — this manuscript makes
// no data-sharing statement, so checklist.pdf should show a "non couvert"
// marker on row 4.

#check("5a")[This trial was funded by the National Research Agency
  (grant #42). The funder had no role in the design, conduct, or reporting
  of the trial.]

// --- deliberate test case: unknown item id ("5c" does not exist in
// CONSORT 2025) — checklist.pdf's Diagnostics block should list it.
#check("5c")[There is no item 5c in CONSORT 2025 — this call exists only to
  exercise the "id inconnu" diagnostic.]

= Introduction

#check("6")[Prior trials suggested a plausible mechanism of action for
  Drug X on outcome Y.]

#check("7")[The primary objective was to determine whether Drug X reduces
  outcome Y compared with placebo, and to characterise its harms.]

= Methods

// --- deliberate test case: blank check() content ---
#check("11")[]

#check("12a")[Adults aged 18-75 with a confirmed diagnosis of condition Z.]

#check("12b")[Participating sites were university hospitals with a
  dedicated research nurse.]

#check("13")[Participants received either Drug X (10 mg once daily) or a
  matching placebo for 12 weeks.]

#check("14")[
  The primary outcome was change in score S from baseline to week 12,
  analysed as a mean difference between groups.
]

// --- deliberate test case: na() declared for an item that is also
// check()'d elsewhere — checklist.pdf's Page cell for 15 should flag the
// conflict instead of silently picking one side.
#check("15")[Harms were monitored via routine adverse-event reporting at
  each study visit.]
#na("15", reason: [Kept only to demonstrate the check()/na() conflict
  diagnostic — a real manuscript would never both check() and na() the
  same item.])

#check("16a")[The sample size of 240 participants was calculated to detect
  a 4-point difference in score S with 90% power.]

== Randomisation

#check("17a")[The allocation sequence was generated by an independent
  statistician using a computer-based random-number generator.]

#check("17b")[Randomisation used permuted blocks of 4 and 6, stratified by
  site.]

#check("18")[Allocation was concealed using sequentially numbered, opaque,
  sealed envelopes prepared by a party independent of recruitment.]

#check("19")[Research nurses enrolling participants had no access to the
  allocation sequence until after enrolment.]

#check("20a")[Participants and outcome assessors were blinded to group
  assignment; care providers were not.]

#check("21a")[Groups were compared for the primary outcome using a
  mixed-effects linear model.]

#check("21b")[All randomised participants were analysed in their assigned
  group, regardless of adherence (intention-to-treat).]

#check("21c")[Missing outcome data were handled by multiple imputation
  under a missing-at-random assumption.]

// --- deliberate test case: na() declared twice for the same item —
// checklist.pdf's Diagnostics block should flag "declared 2 times".
#na("21d", reason: [No subgroup or sensitivity analyses were planned.])
#na("21d", reason: [Duplicate declaration, on purpose, to demonstrate the
  "declared N times" diagnostic.])

#pagebreak()
// The page break above is inserted purely so the second mention of item
// 14 below lands on a different page than the first one in the Methods
// section — demonstrating that an item checked at two different
// locations gets both pages listed (deduplicated, not merged into one).

= Results

// --- deliberate test case: item 14 mentioned again, on a later page ---
#check("14")[
  As stated in the Methods, outcome S was assessed by a rater blinded to
  group assignment.
]

#check("22a")[240 participants were randomly assigned: 120 to each group.]

#check("23a")[Recruitment ran from March 2024 to September 2024, with
  follow-up completed in December 2024.]

#check("25")[@tab-baseline shows baseline characteristics for each group.]

#figure(
  table(
    columns: 3,
    [*Characteristic*], [*Drug X*], [*Placebo*],
    [Age, mean (SD)], [52 (12)], [54 (11)],
    [Female, n (%)], [61 (51%)], [58 (48%)],
  ),
  caption: [Baseline characteristics.],
) <tab-baseline>

#check("26")[
  For the primary outcome, the mean difference between groups was 4.2
  points (95% CI 1.1 to 7.3).
]

#check("27")[No serious adverse events were reported in either group.]

= Discussion

#check("29")[These results are consistent with the hypothesised mechanism
  of action of Drug X, and are broadly in line with prior smaller trials.]

#check("30")[This trial was limited by its single-country setting and its
  12-week follow-up, which may not capture longer-term harms.]
